language: ruby
rvm:
  - 2.4.0
bundler_args: --without production
script:
  - rails db:create db:migrate
  - bundle exec rspec
services:
  - postgresql
addons:
  postgresql: "9.3"
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
os: linux
group: stable
sudo: required
dist: trusty
