language: ruby
rvm:
  - 2.4.0
bundler_args: --without production
script:
  - rails db:create db:migrate
  - bundle exec rspec
services:
  - postgresql
addons:
  postgresql: "9.3"
os: linux
group: stable
dist: precise

