language: ruby
sudo: required
dist: trusty
rvm:
  - 2.4.0
bundler_args: --without production
script:
  - rails db:create db:migrate
  - bundle exec rspec
services:
  - postgresql
addons:
  postgresql: "9.3"
os: linux
group: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
